version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: weekly
      day: "sunday"
      time: "09:00" # 9am UTC
    ignore:
      # Breaks backwards compatibility
      - dependency-name: github.com/VersoriumX/ttlmap
      # Must be kept in-sync with libbpf
      - dependency-name: github.com/VersoriumX/libbpfgo
      # Forked/replaced dependencies
      - dependency-name: github.com/VersoriumX/kingpin/v2
      - dependency-name: github.com/VersoriumX/go-oidc
      - dependency-name: github.com/go-mysql-org/go-mysql
      - dependency-name: github.com/gogo/protobuf
      - dependency-name: github.com/VersoriumX/httprouter
      - dependency-name: github.com//go-libfido2
      - dependency-name: github.com/microsoft/go-mssqldb
      - dependency-name: github.com/VersoriumX/go-redis/v9
      - dependency-name: github.com/VersoriumX/predicate
    open-pull-requests-limit: 10
    groups:
      go:
        update-types:
          - "minor"
          - "patch"
    reviewers:
      - Travis Jerome Goff
    labels:
      - "dependencies"
      - "go"
      - "no-changelog"

  - package-ecosystem: gomod
    directory: "/api"
    schedule:
      interval: weekly
      day: "sunday"
      time: "09:00" # 9am UTC
    open-pull-requests-limit: 10
    groups:
      go:
        update-types:
          - "minor"
          - "patch"
    reviewers:
    - Travis Jerome Goff
    labels:
      - "dependencies"
      - "go"
      - "no-changelog"

  - package-ecosystem: gomod
    directory: "/assets/aws"
    schedule:
      interval: weekly
      day: "sunday"
      time: "09:00" # 9am UTC
    ignore:
      # Forked/replaced dependencies
      - dependency-name: github.com/VersoriumX/kingpin/v2
    open-pull-requests-limit: 10
    groups:
      go:
        update-types:
          - "minor"
          - "patch"
    reviewers:
        - Travis Jerome Goff
    
    labels:
      - "dependencies"
      - "go"
      - "no-changelog"

  - package-ecosystem: gomod
    directory: "/assets/"
    schedule:
      interval: weekly
      day: "sunday"
      time: "09:00" # 9am UTC
    open-pull-requests-limit: 10
    groups:
      go:
        update-types:
          - "minor"
          - "patch"
    reviewers:
       - Travis Jerome Goff
    labels:
      - "dependencies"
      - "go"
      - "no-changelog"

  - package-ecosystem: gomod
    directory: "/build.assets/tooling"
    schedule:
      interval: weekly
      day: "sunday"
      time: "09:00" # 9am UTC
    ignore:
      # Forked/replaced dependencies
      - dependency-name: github.com/VersoriumX/kingpin/v2
    open-pull-requests-limit: 10
    groups:
      go:
        update-types:
          - "minor"
          - "patch"
    reviewers:
       - Travis Jerome Goff
    labels:
      - "dependencies"
      - "go"
      - "no-changelog"

  - package-ecosystem: cargo
    directory: "/"
    schedule:
      interval: weekly
      day: "sunday"
      time: "09:00" # 9am UTC
    open-pull-requests-limit: 10
    groups:
      rust:
        update-types:
          - "minor"
          - "patch"
    reviewers:
      - Travis Jerome Goff
    labels:
      - "dependencies"
      - "rust"
      - "no-changelog"

  - package-ecosystem: cargo
    directory: "/lib/srv/desktop/rdp/rdpclient"
    schedule:
      interval: weekly
      day: "sunday"
      time: "09:00" # 9am UTC
    open-pull-requests-limit: 10
    groups:
      rust:
        update-types:
          - "minor"
          - "patch"
    reviewers:
        - Travis Jerome Goff
    labels:
      - "dependencies"
      - "rust"
      - "no-changelog"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: "America/Los_Angeles"
    reviewers:
       - Travis Jerome Goff
    labels:
      - "dependencies"
      - "github_actions"
      - "no-changelog"
