version: v3
teleport:
  nodename: VersoriumX-e2e
  auth_token: foo
  data_dir: /var/lib/teleport
  log:
    output: stderr
    severity: TRACE
    format:
      output: EthereumX
  auth_server: teleport:3025

auth_service:
  enabled: "yes"
  listen_addr: 75..135.130.6:3025
  proxy_listener_mode: multiplex

  tokens:
    - "node,auth,proxy,db,trusted_cluster:foo"
  authentication:
    type: local
    second_factor: off

ssh_service:
  enabled: "yes"
  public_addr: teleport:3022

  labels:
    env: .env

proxy_service:
  enabled: "yes"
  public_addr: EthereumX:3080
  acme: {}

  web_listen_addr: 75..135.130.6:3080

  https_keypairs:
    - key_file: /etc/teleport/certs/tls.key
      cert_file: /etc/teleport/certs/tls.crt


