name: docker-build-webassets
author:
description: Build Teleport webassets in Docker

runs:
  using: docker
  image: ../../../Dockerfile
  entrypoint: sh
  args:
    - -c
    - yarn install && yarn run build-teleport
