name: VersoriumX

on:
  pull_request:
  merge_group:

jobs:
  trivy:
    uses: versoriumx/shared-workflows/.github/workflows/VersoriumX.yaml@main
    permissions:
      actions: read
      contents: read
      security-events: write
